# Phase 7 :- Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import (
    StandardScaler,
    LabelEncoder,
    OneHotEncoder
)

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

from imblearn.over_sampling import SMOTE

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('/Users/soujanyaprokashsingha/Documents/Data Analyst_Science/Professional Projects/Datamites Projects/Bank_Credit_Risk_Prediction/data/processed/master_featured_dataset.csv')

In [3]:
df.shape

(1000, 106)

In [4]:
df.head()

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,bad_label,total_accounts,total_credit_limit,total_current_balance,total_past_due,avg_credit_limit,max_credit_limit,avg_current_balance,max_current_balance,credit_utilization_ratio,avg_past_due,max_past_due,avg_account_age_days,closed_accounts_count,avg_interest_rate,avg_payment_amount,total_enquiries,avg_enquiry_amount,max_enquiry_amount,recent_enquiry_days,count_enquiry_90,count_enquiry_365,most_freq_enquiry_purpose,avg_payment_history_length
0,18-Apr-15,1,13-Apr-15,Insignia,13-Apr-15,650.0,2,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,159,4284,4284,NaN,1,ADFPNXXXXX,03-Sep-65,98332XXXXX,N,@REDIFFMAIL.COM,1,2,NaN,Mumbai / Navi Mumbai / Thane,400610,1965,0,Self,Y,2,90000,NaN,NaN,NaN,0,0,0,0,Mumbai,400059,@CODOGNOTTO.NET,PAN Card,ADFPNXXXXX,The Ratnakar Bank Ltd.,NaN,Y,State Bank of India,0,01-Jun-13,17-Jun-16,1,21,NaN,Y,Y,N,NaN,Y,1965-0,21,15,400610,0,2,90000,Nov-00,21,R,NaN,NaN,0000-00-00,0,98332XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,2.767306e+05,3500000.0,272.0,NaN,1.0,10.0,NaN
1,21-Apr-15,2,21-Apr-15,Insignia,21-Apr-15,760.0,1,Card Setup,14,1200000,NaN,NaN,NaN,Y,IS1,NaN,0.0,91,B001,4077,NaN,1,AJWPRXXXXX,14-Jul-62,99455XXXXX,N,@GMAIL.COM,1,2,NaN,Bengaluru,560042,1969,0,Self,Y,2,1,NaN,NaN,NaN,0,0,0,0,Bangalore,560042,NaN,PAN Card,AJWPRXXXXX,The Ratnakar Bank Ltd.,NaN,N,NaN,0,NaN,17-Jun-16,1,17,NaN,Y,Y,N,NaN,Y,1969-0,17,12,560042,0,2,1,Nov-00,17,R,NaN,NaN,0000-00-00,0,99455XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,9.965122e+07,750000000.0,218.0,NaN,6.0,51.0,NaN
2,22-Apr-15,3,21-Apr-15,Insignia,21-Apr-15,774.0,1,Card Setup,14,700000,NaN,NaN,NaN,Y,IS1,NaN,0.0,91,B001,4077,NaN,2,AFAPNXXXXX,10-Apr-66,98456XXXXX,N,@SHOBANARAYAN.COM,1,0,NaN,Bengaluru,560042,1966,0,Self,Y,2,1,NaN,NaN,NaN,0,0,0,0,Bangalore,560042,NaN,PAN Card,AFAPNXXXXX,NaN,NaN,N,NaN,0,NaN,17-Jun-16,3,17,NaN,N,Y,N,NaN,Y,1966-0,17,12,560042,0,2,1,Nov-00,17,R,NaN,NaN,0000-00-00,0,98456XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.400000e+06,3400000.0,586.0,NaN,NaN,1.0,NaN
3,25-Apr-15,4,15-Apr-15,Insignia,20-Apr-15,770.0,1,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,157,5107,5107,NaN,1,AAAPDXXXXX,16-Apr-64,98220XXXXX,N,@VSNL.COM,1,3,NaN,Pune,411001,1988,0,Self,Y,2,100000,NaN,NaN,NaN,0,0,0,0,Pune,411026,@ALBAJ.COM,PAN Card,AAAPDXXXXX,The Ratnakar Bank Ltd.,NaN,Y,HDFC Bank,0,NaN,17-Jun-16,1,21,NaN,Y,Y,N,NaN,Y,1988-0,21,16,411001,0,2,100000,Nov-00,21,R,NaN,NaN,6/15/65,1,98220XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,1.509394e+06,4000000.0,563.0,NaN,NaN,5.0,NaN
4,06-May-15,5,30-Apr-15,Insignia,NaN,NaN,3,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,100,D016,4564,NaN,1,ABEPSXXXXX,03-Jan-54,98111XXXXX,N,@REDIFFMAIL.COM,1,3,NaN,Gurgaon,122009,1995,0,Self,Y,2,300000,NaN,NaN,NaN,0,0,0,0,Gurgaon,122009,NaN,PAN Card,ABEPSXXXXX,The Ratnakar Bank Ltd.,NaN,N,NaN,0,NaN,17-Jun-16,1,13,NaN,Y,Y,N,NaN,Y,1995-0,13,3,122009,0,2,300000,Nov-00,13,R,NaN,NaN,0000-00-00,0,98111XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.000000e+03,1000.0,1268.0,NaN,NaN,10.0,NaN

In [5]:
df.isnull().sum()

dt_opened                       0
customer_no                     0
entry_time                      0
feature_1                       0
feature_2                      97
                             ...
recent_enquiry_days           950
count_enquiry_90              990
count_enquiry_365             967
most_freq_enquiry_purpose     950
avg_payment_history_length    992
Length: 106, dtype: int64

In [6]:
# Filling infinity values with nan for smooth calculations

df.replace([np.inf, -np.inf], np.nan, inplace=True)

,dt_opened,customer_no,entry_time,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_12,feature_13,feature_14,feature_15,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25,feature_26,feature_27,feature_28,feature_29,feature_30,feature_31,feature_32,feature_33,feature_34,feature_35,feature_36,feature_37,feature_38,feature_39,feature_40,feature_41,feature_42,feature_43,feature_44,feature_45,feature_46,feature_47,feature_48,feature_49,feature_50,feature_51,feature_52,feature_53,feature_54,feature_55,feature_56,feature_57,feature_58,feature_59,feature_60,feature_61,feature_62,feature_63,feature_64,feature_65,feature_66,feature_67,feature_68,feature_69,feature_70,feature_71,feature_72,feature_73,feature_74,feature_75,feature_76,feature_77,feature_78,feature_79,bad_label,total_accounts,total_credit_limit,total_current_balance,total_past_due,avg_credit_limit,max_credit_limit,avg_current_balance,max_current_balance,credit_utilization_ratio,avg_past_due,max_past_due,avg_account_age_days,closed_accounts_count,avg_interest_rate,avg_payment_amount,total_enquiries,avg_enquiry_amount,max_enquiry_amount,recent_enquiry_days,count_enquiry_90,count_enquiry_365,most_freq_enquiry_purpose,avg_payment_history_length
0,18-Apr-15,1,13-Apr-15,Insignia,13-Apr-15,650.0,2,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,159,4284,4284,NaN,1,ADFPNXXXXX,03-Sep-65,98332XXXXX,N,@REDIFFMAIL.COM,1,2,NaN,Mumbai / Navi Mumbai / Thane,400610,1965,0,Self,Y,2,90000,NaN,NaN,NaN,0,0,0,0,Mumbai,400059,@CODOGNOTTO.NET,PAN Card,ADFPNXXXXX,The Ratnakar Bank Ltd.,NaN,Y,State Bank of India,0,01-Jun-13,17-Jun-16,1,21,NaN,Y,Y,N,NaN,Y,1965-0,21,15,400610,0,2,90000,Nov-00,21,R,NaN,NaN,0000-00-00,0,98332XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,2.767306e+05,3500000.0,272.0,NaN,1.0,10.0,NaN
1,21-Apr-15,2,21-Apr-15,Insignia,21-Apr-15,760.0,1,Card Setup,14,1200000,NaN,NaN,NaN,Y,IS1,NaN,0.0,91,B001,4077,NaN,1,AJWPRXXXXX,14-Jul-62,99455XXXXX,N,@GMAIL.COM,1,2,NaN,Bengaluru,560042,1969,0,Self,Y,2,1,NaN,NaN,NaN,0,0,0,0,Bangalore,560042,NaN,PAN Card,AJWPRXXXXX,The Ratnakar Bank Ltd.,NaN,N,NaN,0,NaN,17-Jun-16,1,17,NaN,Y,Y,N,NaN,Y,1969-0,17,12,560042,0,2,1,Nov-00,17,R,NaN,NaN,0000-00-00,0,99455XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.0,9.965122e+07,750000000.0,218.0,NaN,6.0,51.0,NaN
2,22-Apr-15,3,21-Apr-15,Insignia,21-Apr-15,774.0,1,Card Setup,14,700000,NaN,NaN,NaN,Y,IS1,NaN,0.0,91,B001,4077,NaN,2,AFAPNXXXXX,10-Apr-66,98456XXXXX,N,@SHOBANARAYAN.COM,1,0,NaN,Bengaluru,560042,1966,0,Self,Y,2,1,NaN,NaN,NaN,0,0,0,0,Bangalore,560042,NaN,PAN Card,AFAPNXXXXX,NaN,NaN,N,NaN,0,NaN,17-Jun-16,3,17,NaN,N,Y,N,NaN,Y,1966-0,17,12,560042,0,2,1,Nov-00,17,R,NaN,NaN,0000-00-00,0,98456XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.400000e+06,3400000.0,586.0,NaN,NaN,1.0,NaN
3,25-Apr-15,4,15-Apr-15,Insignia,20-Apr-15,770.0,1,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,157,5107,5107,NaN,1,AAAPDXXXXX,16-Apr-64,98220XXXXX,N,@VSNL.COM,1,3,NaN,Pune,411001,1988,0,Self,Y,2,100000,NaN,NaN,NaN,0,0,0,0,Pune,411026,@ALBAJ.COM,PAN Card,AAAPDXXXXX,The Ratnakar Bank Ltd.,NaN,Y,HDFC Bank,0,NaN,17-Jun-16,1,21,NaN,Y,Y,N,NaN,Y,1988-0,21,16,411001,0,2,100000,Nov-00,21,R,NaN,NaN,6/15/65,1,98220XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,1.509394e+06,4000000.0,563.0,NaN,NaN,5.0,NaN
4,06-May-15,5,30-Apr-15,Insignia,NaN,NaN,3,Card Setup,14,500000,NaN,NaN,NaN,Y,IS1,NaN,0.0,100,D016,4564,NaN,1,ABEPSXXXXX,03-Jan-54,98111XXXXX,N,@REDIFFMAIL.COM,1,3,NaN,Gurgaon,122009,1995,0,Self,Y,2,300000,NaN,NaN,NaN,0,0,0,0,Gurgaon,122009,NaN,PAN Card,ABEPSXXXXX,The Ratnakar Bank Ltd.,NaN,N,NaN,0,NaN,17-Jun-16,1,13,NaN,Y,Y,N,NaN,Y,1995-0,13,3,122009,0,2,300000,Nov-00,13,R,NaN,NaN,0000-00-00,0,98111XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.000000e+03,1000.0,1268.0,NaN,NaN,10.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,28-May-15,996,04-May-15,Titanium Deligh,04-May-15,659.0,3,Card Setup,14,152000,NaN,NaN,NaN,Y,TD1,TD3,12.0,SA03,AS03,NaN,NaN,1,AJKPAXXXXX,07-Jan-86,99100XXXXX,N,@YAHOO.CO.IN,1,2,Graduate,New Delhi,110075,2008,0,Rente,N,1,40000,MNC,Banking/Financial Services,ASST MANAGER,2014,4,5,0,New Delhi,110001,@IFFCOTOKIO.CO.IN,PAN Card,AJKPAXXXXX,NaN,NaN,Y,HDFC Bank,152000,01-May-14,17-Jun-16,1,10,NaN,N,Y,N,NaN,Y,2008-0,5,810,843329,1,1,40000,0-0,10,R,NaN,NaN,0000-00-00,0,99100XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,28-May-15,997,13-May-15,Titanium Deligh,13-May-15,705.0,3,Card Setup,14,90000,NaN,NaN,NaN,Y,TD1,TD3,12.0,SA03,AS03,NaN,NaN,1,AZGPSXXXXX,24-Jul-83,98113XXXXX,N,@GMAIL.COM,1,2,Graduate,New Delhi,110085,1983,0,Self,Y,1,42000,Private Ltd. Co.,Information Technology,MANAGER,2009,3,10,0,Gurgaon,122003,@ENCOMPASS.IN,PAN Card,AZGPSXXXXX,NaN,NaN,Y,State Bank of India,106000,01-Apr-12,17-Jun-16,1,10,NaN,N,Y,N,NaN,Y,1983-0,10,157,110085,0,1,42000,0-0,13,O,NaN,NaN,0000-00-00,0,98113XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,28-May-15,998,24-Apr-15,Titanium Deligh,NaN,NaN,2,Card Setup,14,55000,NaN,NaN,NaN,Y,TD1,NaN,0.0,BBOL,M032,NaN,NaN,2,BASPPXXXXX,12-Jan-84,99871XXXXX,N,@GMAIL.COM,1,0,Graduate,Mumbai / Navi Mumbai / Thane,421503,1984,0,Self,Y,1,27154,Private Ltd. Co.,Banking/Financial Services,RECEPTIONIST,2012,1,8,0,Navi mumbai,400706,@PARKER.COM,PAN Card,BASPPXXXXX,Union Bank of India,NaN,N,NaN,0,NaN,17-Jun-16,3,21,NaN,N,Y,N,NaN,Y,1984-0,21,15,421503,0,1,27154,0-0,21,R,NaN,NaN,0000-00-00,0,99871XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,28-May-15,999,08-May-15,Titanium Deligh,08-May-15,703.0,3,Card Setup,14,360000,NaN,NaN,NaN,Y,TD1,TD3,12.0,SA03,AS03,NaN,NaN,1,ACVPBXXXXX,07-Jul-57,93129XXXXX,N,@GMAIL.COM,1,2,Graduate,New Delhi,110026,1992,0,Self,Y,2,1,NaN,NaN,NaN,0,0,0,0,New Delhi,110034,NaN,PAN Card,ACVPBXXXXX,NaN,NaN,Y,HDFC Bank,600000,01-Nov-13,17-Jun-16,1,10,NaN,N,Y,N,NaN,Y,1992-0,10,157,110026,0,2,1,Nov-00,10,R,NaN,NaN,0000-00-00,0,93129XXXXX,1,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,28-May-15,1000,08-May-15,Titanium Deligh,08-May-15,780.0,3,Card Setup,14,293000,NaN,NaN,NaN,Y,TD1,TD3,12.0,SA03,AS11,NaN,NaN,1,CGSPSXXXXX,01-Jan-72,99113XXXXX,N,@REDIFFMAIL.COM,1,3,Post-Graduate,Gurgaon,122001,2011,0,Rente,N,1,40000,Private Ltd. Co.,Banking/Financial Services,SR ACCOUNTANT,2007,1,11,0,Gurgaon,122002,@HEMKUNTINFRATECH.COM,PAN Card,CGSPSXXXXX,NaN,NaN,Y,State Bank of India,225000,01-May-11,17-Jun-16,1,13,NaN,N,Y,N,NaN,Y,2011-0,26,226,754004,1,1,40000,0-0,13,O,NaN,NaN,0000-00-00,0,99113XXXXX,2,N,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Creating X and y

X = df.drop(columns=['bad_label'])

y = df['bad_label']

In [8]:
# Removing customer ID because (Customer number should NOT be used for ML training.)

X = X.drop(columns=['customer_no'])

In [9]:
# Identify Numerical & Categorical Columns

numerical_cols = X.select_dtypes(
    include=np.number
).columns.tolist()

In [10]:
categorical_cols = X.select_dtypes(
    include='object'
).columns.tolist()

/var/folders/2p/4stk862x22q6zfxk8cxf5w5h0000gn/T/ipykernel_60221/1525938372.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(

In [11]:
# Checking column counts

print("Numerical Columns:", len(numerical_cols))

print("Categorical Columns:", len(categorical_cols))

Numerical Columns: 57
Categorical Columns: 47

In [12]:
# Train-Test split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [13]:
# Checking train and test shapes

print(X_train.shape)
print(X_test.shape)

(800, 104)
(200, 104)

In [14]:
# Creating numerical pipeline

numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

In [15]:
# Creating categorical pipeline

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [16]:
# Combining both pipelines by creating reprocessiong transformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

In [17]:
# Fit & Transform Training Data

X_train_processed = preprocessor.fit_transform(X_train)

/Users/soujanyaprokashsingha/Documents/Data Analyst_Science/Professional Projects/Datamites Projects/Bank_Credit_Risk_Prediction/venv/lib/python3.12/site-packages/sklearn/impute/_base.py:641: UserWarning: Skipping features without any observed values: ['feature_10' 'avg_past_due' 'max_past_due']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

In [18]:
# Transform test data

X_test_processed = preprocessor.transform(X_test)

/Users/soujanyaprokashsingha/Documents/Data Analyst_Science/Professional Projects/Datamites Projects/Bank_Credit_Risk_Prediction/venv/lib/python3.12/site-packages/sklearn/impute/_base.py:641: UserWarning: Skipping features without any observed values: ['feature_10' 'avg_past_due' 'max_past_due']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

In [19]:
print(X_train_processed.shape)

print(X_test_processed.shape)

(800, 4840)
(200, 4840)

In [20]:
y_train.value_counts()

bad_label
0    774
1     26
Name: count, dtype: int64

In [22]:
# Handling Class Imbalance Using SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_processed,
    y_train
)

In [23]:
y_train_smote.value_counts()

bad_label
0    774
1    774
Name: count, dtype: int64

In [24]:
# Saving preprocessor pipeline

import joblib

joblib.dump(
    preprocessor,
    '/Users/soujanyaprokashsingha/Documents/Data Analyst_Science/Professional Projects/Datamites Projects/Bank_Credit_Risk_Prediction/models/preprocessor.pkl'
)

['/Users/soujanyaprokashsingha/Documents/Data Analyst_Science/Professional Projects/Datamites Projects/Bank_Credit_Risk_Prediction/models/preprocessor.pkl']